name: Weekly Actions Update Check

on:
  workflow_dispatch:
  push:
    branches: [main]
#   schedule:
#     - cron: '0 2 * * 1'

jobs:
  check-updates:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout repo on branch: ${{ github.REF }}' 
        uses: actions/checkout@v4
        with:
          ref: ${{ github.REF }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Get User Name
        id: userid
        run: |
          user="${{ github.actor }}"
          gitur=$(echo $user )
          echo "gitur=$gitur" >> $GITHUB_OUTPUT

      - name: Install actions-up
        run: npm install -g actions-up

      - name: Check for outdated actions
        id: check
        run: | 
          actions-up --dry-run > actions-up-raw.txt 2>&1 || true
          if [ -s actions-up-raw.txt ]; then
            echo "updates-found=true" >> $GITHUB_OUTPUT
          else
            echo "updates-found=false" >> $GITHUB_OUTPUT
          fi

      - name: Update workflow actions
        if: steps.check.outputs['updates-found'] == 'true'
        run: |
          echo "Checking and updating GitHub Actions..."
          npx actions-up -y || true

      - name: Configure Git
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        working-directory: ${{github.workspace}}
        run: |
          if git status --porcelain | grep .; then
            git checkout main
            git config user.name "${{steps.userid.outputs.gitur}}"
            git config user.email "${{steps.userid.outputs.gitur}}}@gmail.com"
          fi

      - name: Commit Changes
        if: steps.check.outputs['updates-found'] == 'true'
        run: |
          git add .github/workflows || true
          if git diff --checked --quiet; then
            echo "No update to commit"
            exit 0
          fi

      - name: Push branch using Classic PAT
        if: steps.check.outputs['updates-found'] == 'true'
        run: |
          git config --global credential.helper

          git push "https://${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}HEAD:main"

      - name: Clean up workspace
        if: always()
        run: |
          ls -ltra 
          echo "Cleaning up workspace and hidden files/folders"
          rm -rf ./* ./.[^.] ./..?*
          ls -ltra
      
